#!/usr/bin/php

<?php

// connect to memcache
$memcache = new Memcache;
$memcache->connect('localhost', 11211) or die("Could not connect to memcache");

$memcache->set('cs50_can_ask', false);
exit();

?>
