#!/usr/bin/php

<?php

// connect to memcache
$memcache = new Memcache;
$memcache->connect('localhost', 11211) or die("Could not connect to memcache");

// get all course schedules
mysql_connect('localhost', 'cs50help', 'cs50help');
mysql_select_db('cs50help');
$query = 'SELECT schedule_url, url FROM courses';
$result = mysql_query($query);

// iterate over courses
while ($row = mysql_fetch_assoc($result)) {
	// fetch XML of schedule data
	$course = $row['url'];
	$curl = curl_init($row['schedule_url']);
	curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
	$schedule_xml = new SimpleXMLElement(curl_exec($curl));
	curl_close($curl);

	// iterate over entries
	$can_ask = 0;
	foreach ($schedule_xml->entry as $event) {
		// extract date from gcal string
		preg_match('/When: (\w+) (\w+) (\d+), (\d+) ([0-9apm:]+) to ([0-9apm:]+)/', (string)$event->summary, $matches);
		if (count($matches) == 7) {
			$start = "{$matches[1]} {$matches[2]} {$matches[3]}, {$matches[4]} {$matches[5]}";
			$end = "{$matches[1]} {$matches[2]} {$matches[3]}, {$matches[4]} {$matches[6]}";
		}
		else {
			preg_match('/When: (\w+) (\w+) (\d+), (\d+) ([0-9apm:]+) to (\w+) (\w+) (\d+), (\d+) ([0-9apm:]+)/', (string)$event->summary, $matches);
			if (count($matches) == 11) {
				$start = "{$matches[1]} {$matches[2]} {$matches[3]}, {$matches[4]} {$matches[5]}";
				$end = "{$matches[6]} {$matches[7]} {$matches[8]}, {$matches[9]} {$matches[10]}";
			}
		}

		// if current timestamp falls in an OH slot, then students can ask questions
		if (strtotime($start) <= time() && strtotime($end) >= time()) {
			$can_ask = 1;
			break;

		}
	}

	// set memcache flag
	$memcache_key = $course . '_can_ask';
	echo "{$course}: {$can_ask}\n";
	$memcache->set($memcache_key, $can_ask);
}

?>
